version: '3.3'

services:
  db:
    image: mysql:5.7
    container_name: mysql-scheduling-bot
    restart: always
    environment:
      MYSQL_DATABASE: 'scheduling_bot'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
    ports:
      - "9000:9000"